# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
data = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
data1 = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
data1.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
data1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)

1.18.1


7. Print the dimension of the array in question 3


In [7]:
data1.ndim

1

8. Create a boolean array with all the True values

In [14]:
boolean_arr = np.ones( 10 , dtype = bool)
boolean_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [10]:
array1 = np.array([[2,2], [3,3]])
array1.ndim

2

10. Create a three dimensional array



In [11]:
array1 = np.array([[1,1,1],[2,2,2], [3,3,3]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [16]:
data2 = np.arange(1, 20)
print("Original array:")
print (data2)
print("Reverse array:")
data2 = data2[::-1]
data2

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse array:


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [18]:
arr1 = np.zeros(10)
print(arr1)
print("Update fifth value to 1")
arr1[4] = 1
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [19]:
arr2 = np.identity(3)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
print("after converting the data type ")
arr = arr.astype('float64')
arr.dtype

int32
after converting the data type 


dtype('float64')

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [34]:
import numpy as np
arr1 = np.array([[1., 2., 3.],
                 
                 [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],
                 
                 [7., 2., 12.]])
arr3 = np.multiply(arr1, arr2)
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [36]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3 = (arr1 == arr2)
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [47]:
arr = np.array([1,2,3,5,9,6,3,4,5,6,6,7,7,8,9])
arr[arr%2 ==1]

array([1, 3, 5, 9, 3, 5, 7, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [52]:
arr = np.array([1,2,3,5,9,6,3,4,5,6,6,7,7,8,9])
arr[arr%2 ==1] = -1
arr

array([-1,  2, -1, -1, -1,  6, -1,  4, -1,  6,  6, -1, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [12]:
import numpy as np
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [72]:
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [109]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [111]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [125]:
arr2d = np.array([[1,3,4,2,5],[6,7,8,9,0]])
print(arr2d.ndim)
arr2d[0]

2


array([1, 3, 4, 2, 5])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [126]:
arr2d = np.array([[1,3,4,2,5],[6,7,8,9,0]])
print(arr2d.ndim)
arr2d[1]

2


array([6, 7, 8, 9, 0])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [154]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr[0:2, 2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [161]:
arr = np.random.randn(10,10)
print(arr)
print(f"minimum value of the array is {arr.min()} ")
print(f"maximum value of the array is {arr.max()} ")

[[ 0.09506024  1.22451439  1.17191686 -1.02446415 -0.3767817  -0.50926211
  -0.16265564  0.76856935  1.67416038  0.09231384]
 [ 0.75640363 -2.48710332 -0.47975706  0.03854092 -1.32503747  0.17439824
   1.02121625 -2.27400254  1.69372744  2.17834243]
 [ 0.60610759  2.87349454  0.43852876  0.72954523  0.89005451  2.3434759
   1.33013778 -0.23050968  0.61043345 -1.49192853]
 [ 0.42431012  1.02705215  0.32395225  0.13817283  1.09463647 -2.61984125
   0.12196547  0.09222184 -0.9684739  -0.69568098]
 [-0.84260229 -1.8246811   0.18405223  0.7551478   0.14320231 -0.33575023
  -0.2973813   0.38386383  1.51264317  0.49525527]
 [ 1.31532471 -2.66421409 -1.00472265  0.29953632 -1.01478408 -0.82745086
  -1.20946685 -1.32584663 -0.04454418  0.31537689]
 [ 0.39800765  0.84414089  1.65131306  1.57527401  0.70420967  1.02523236
   0.56512855 -0.82096178  2.47032954  0.78587197]
 [ 0.18452997 -1.09868362 -1.14620441  0.63220452  0.02803059 -0.95853297
  -0.29013918 -0.40558819 -0.88815483 -0.17754306]
 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [162]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [166]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
x = data[names != "Will"] 
x

array([[ 1.4533799 ,  0.92135096, -1.3732312 , -0.59087768],
       [ 0.132447  ,  0.4402212 ,  0.89653266, -0.29353398],
       [-0.03380972,  0.15910626,  0.21234786,  0.39538268],
       [ 1.95454824,  0.16774749,  0.56767643,  2.56180497],
       [-1.07051635, -0.81350013, -0.99642117,  0.36703682]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [214]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names != ("Will" and "Joe")] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.05895104,  1.50007271,  0.16019416,  1.76169127],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.65709443, -1.28584695, -0.3674925 ,  0.77641392],
       [-0.10554672,  0.66137724, -0.80546989,  0.69123814]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [174]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13],[14,15,0]])
print(arr.shape)
print(arr.ndim)

(5, 3)
2


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [180]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
arr2.shape

(2, 2, 4)

33. Swap axes of the array you created in Question 32

In [194]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
np.swapaxes(arr2,0,2)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [222]:
arr3 = np.arange(10)
np.sqrt(arr3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [234]:
arr4 = np.random.randn(12)
arr5 = np.random.randn(12)
print(arr4)
print(arr5)
np.maximum.reduce([arr4,arr5])

[-0.79971949  0.35764351  0.74284804 -0.137484   -0.07348051 -0.22423268
  1.05698464 -0.30648169  1.74424601 -2.56387512  0.02112406  0.64198509]
[ 0.25457777 -1.38426725  0.85455443  0.94728818  0.92589943 -1.50693732
  0.30997279 -1.77063232 -2.05170369  1.36451148  0.60316873 -1.74821546]


array([ 0.25457777,  0.35764351,  0.85455443,  0.94728818,  0.92589943,
       -0.22423268,  1.05698464, -0.30648169,  1.74424601,  1.36451148,
        0.60316873,  0.64198509])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [246]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [247]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [30]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray[0:3])
sampleArray = np.delete(sampleArray, 1 , 1)
print(sampleArray)
newColumn = np.array([[10,10,10]])
NewArr = np.insert(sampleArray,1, newColumn, axis = 1 )
print(NewArr)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [248]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [262]:
matarr = np.random.randn(20,20)
print(matarr)
matarr.cumsum()

[[ 1.11995663e+00  1.38302498e+00  5.17943879e-01  2.03282660e-01
   7.59284361e-01 -1.01249118e+00 -1.26718223e+00 -1.35006760e+00
   4.62163432e-01 -1.43901656e+00  8.46829704e-01  6.58164351e-01
   3.14873495e-01 -1.04552815e-01 -1.28305861e+00 -4.34608540e-01
  -1.16478009e-01 -9.43350998e-01  1.55348594e+00 -1.10025501e+00]
 [ 3.94007122e-01 -2.81697178e+00 -4.91561772e-01  8.93949978e-01
  -8.94210221e-01 -3.77970789e-03  1.27083016e+00 -8.24069275e-01
  -7.33232538e-01  1.22297222e+00 -1.20142133e+00 -1.46530372e+00
  -7.95635743e-01 -9.54180610e-01  2.44068728e-02 -3.10288775e-01
  -2.54143606e-01 -1.70255736e+00 -1.23527176e+00 -1.56700511e+00]
 [ 4.42262572e-01  1.78072176e+00 -1.20760624e+00 -5.36935105e-01
  -1.74168802e+00 -4.83869310e-01  2.44096404e-01 -1.03494376e+00
   3.32987562e-01  1.04974101e+00 -2.10025292e-01 -7.24270294e-02
   1.16157841e+00 -2.98893879e-01 -1.12892067e+00 -3.04150804e-02
  -1.60881180e-01  1.95246309e+00 -1.23223988e+00 -9.33516640e-02]
 [-1.62

array([  1.11995663,   2.50298161,   3.02092549,   3.22420815,
         3.98349251,   2.97100133,   1.7038191 ,   0.35375151,
         0.81591494,  -0.62310162,   0.22372808,   0.88189243,
         1.19676593,   1.09221311,  -0.1908455 ,  -0.62545404,
        -0.74193205,  -1.68528305,  -0.13179711,  -1.23205211,
        -0.83804499,  -3.65501677,  -4.14657854,  -3.25262857,
        -4.14683879,  -4.15061849,  -2.87978833,  -3.70385761,
        -4.43709015,  -3.21411792,  -4.41553925,  -5.88084297,
        -6.67647872,  -7.63065933,  -7.60625245,  -7.91654123,
        -8.17068483,  -9.87324219, -11.10851395, -12.67551906,
       -12.23325649, -10.45253473, -11.66014097, -12.19707607,
       -13.93876409, -14.4226334 , -14.178537  , -15.21348076,
       -14.8804932 , -13.83075219, -14.04077749, -14.11320451,
       -12.95162611, -13.25051998, -14.37944066, -14.40985574,
       -14.57073692, -12.61827383, -13.85051372, -13.94386538,
       -15.56961362, -15.63773361, -15.38416212, -15.34